version: "3.7"

networks:
  tillos-network:
    external: true
    driver: bridge

services:
  mis-whatsapp-api:
    build:
      context: .
      dockerfile: .docker/dockerfiles/Dockerfile
    container_name: mis-whatsapp-api
    tty: true
    ports:
      - 3003:3003
    environment:
      NODE_ENV: development
      PORT: 3003
    restart: on-failure
    volumes:
      - .:/usr/mis-whatsapp-api/app
    extra_hosts:
      - host.docker.internal:host-gateway